name: greep
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.2.2+8

environment:
  sdk: ">=2.16.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter
  device_preview:
  flutter_screenutil:
  flutter_svg:
  stacked:
  stacked_hooks:
  stacked_services:
  stacked_themes: 
  shared_preferences: 
  flutter_secure_storage: ^5.0.2
  intl: ^0.17.0
  flutter_share: ^2.0.0
  badges: ^2.0.2
  google_fonts: ^3.0.1
  flutter_slidable: ^2.0.0
  splashscreen: ^1.3.5
  image_picker: ^0.8.4
  dio: ^4.0.6
  http: ^0.13.4
  shimmer: ^2.0.0
  flutter_datetime_picker: ^1.5.1
  bloc: ^7.2.1
  http_parser: ^4.0.1
  mime: ^1.0.2
  pin_code_fields: ^7.3.0
  flutter_bloc: ^7.2.1
  uuid: ^3.0.5
  pull_to_refresh: ^2.0.0
  cached_network_image: ^3.1.0
  get_time_ago: ^1.0.9
  get_it: ^7.2.0
  in_app_update: ^3.0.0
  connectivity_plus: ^2.3.6
  flutter_native_splash: ^2.1.0
  get: ^4.3.8
  flutter_local_notifications:
  permission_handler: ^10.0.0
  cloud_firestore: any
  equatable: ^2.0.3
  cupertino_icons: ^1.0.2
  fl_chart: ^0.55.2
  flutter_dotenv: ^5.0.2
  flutter_typeahead: ^4.0.0
  firebase_core:
  firebase_auth:
  firebase_messaging: ^12.0.1
  google_sign_in:
  upgrader: ^4.6.1
  sign_in_with_apple:


dev_dependencies:
  build_runner:
  freezed: 
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.1
  flutter_launcher_icons: ^0.9.2
  hive_generator: ^1.1.1
  mocktail: ^0.3.0

flutter_icons:
  android: "launcher_icon"
  ios: true
  image_path: "assets/icons/appicon.png"

flutter:

  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - assets/images/
    - assets/icons/
    - .env

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware.

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  fonts:
    - family: Poppins-Bold
      fonts:
        - asset: assets/fonts/Poppins-Bold.ttf
    - family: Poppins-Medium
      fonts:
        - asset: assets/fonts/Poppins-Medium.ttf
    - family: Poppins-Regular
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 100
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 200
        - asset: assets/fonts/Poppins-Light.ttf
          weight: 300
        - asset: assets/fonts/Poppins-Regular.ttf
          weight: 400
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 900
  #
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
